-- Attempt on Unified Data Base, based on XWS (dropped after w1, too much hassle) and FFG conversion table
customShipDB={}
customShipDB[0]={['name']='',['Hull']=0,['Shield']=0,['size']='small',['agi']=1,['Energy']=0,['XWS']='',['Fac']={[0]=true},['arcs']={fixed = { range=3, type = {'front'}}}}

customShipDB['tyewing']={
    name = 'TYE-Wing',
    Hull = 3,
    Shield = 0,
    size = 'small',
    agi = 1,
    XWS = 'tyewing',
    newSpawner = true,
    textures = {
      hiredgun = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/btla4ywing/Textures/hiredgun.png',
    },
    Fac = {[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/btla4ywing/btla4_ywing.obj',
    moveSet = {'bbl1', 'bs1', 'bbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rs4','rk4'},
    keywords = {'TYE-Wing', 'Ugly'}
}

customShipDB['tietrifighter']={
    name = 'TIE Tri Fighter',
    Hull = 2,
    Shield = 2,
    size = 'small',
    agi = 3,
    XWS = 'tietrifighter',
    newSpawner = true,
    textures = {
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiephphantom/textures/tiephphantomgrey.jpg',
    },
    Fac = {[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiephphantom/Tie%20Phantom.obj',
    moveSet = {'bbl1','ws1','bbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3t','wtl3','wbl3','bs3','wbr3','wtr3','rtr3t','ws4','rk4','ws5'},
    keywords = {'TIE', 'Ugly'}
}

return customShipDB
